export const MOCK_STATS = {
  activeThreatsCount: 2,
  exposureAtRisk: '₹3.7M – ₹5.2M',
  exposurePrevented: '₹8.9M',
  avgTimeToContainment: '141s',
  totalEntitiesTracked: 136,
  networkStatus: 'DEFCON-3 // ACTIVE CONTAINMENT',
  normalTrafficRatio: '99.4%',
  suppressionCount: 1,
};

export const MOCK_MODEL_HEALTH = {
  lastEvaluated: '1m ago (17:40 UTC)',
  modelArchitecture: 'LightGBM Gradient Boosted Ensemble + Graph Temporal Engine v4.2.1',
  pointInTime: {
    precision: '61.30%',
    precisionVal: 0.6130,
    recall: '98.55%',
    recallVal: 0.9855,
    f1: '75.59%',
    f1Val: 0.7559,
    aucRoc: '0.9598',
    aucRocVal: 0.9598,
    fpr: '11.76%',
    fprVal: 0.1176,
    testSetSize: 3479,
    fraudPrevalence: '15.9%',
    scoringLatencyP95: '11.8ms',
    dataDriftPsi: '0.012 (Stable)',
  },
  campaignDetection: {
    avgTimeToContainment: '141.5s',
    avgTimeToContainmentSec: 141.5,
    countsByStatus: {
      forming: 2,
      watchlist: 1,
      contained: 2,
      total: 5,
    },
    exposureAtRisk: '₹3.7M – ₹5.2M',
    exposureAtRiskDetail: '₹3,700,000 – ₹5,200,000 across 2 active forming campaigns',
    exposurePrevented: '₹8.9M',
    exposurePreventedDetail: '₹8,900,000 across 2 historically contained attacks',
    populationDisclaimer:
      'Exposure at risk and exposure prevented cover separate campaign populations (active vs. resolved) and are never combined into a ratio.',
  },
};

export const MOCK_CAMPAIGNS = [
  {
    id: 'camp-7f8a-9921',
    name: 'Voucher Abuse Syndicate',
    merchant: 'Steam Games & Vouchers',
    category: 'digital_goods',
    status: 'forming',
    score: 0.94,
    confidence: 0.96,
    detectedAt: '2m ago',
    entryPoint: 'Coordinated emulator voucher farm probing across 35 virtual accounts with VPN egress in Romania',
    entityCount: 35,
    exposureLow: 1800000,
    exposureHigh: 2600000,
    exposureFormatted: '₹1.8M – ₹2.6M',
    currentObserved: '₹525,000',
    exposureConfidence: 0.92,
    recommendedPolicy: 'CONTAIN',
    recommendedPolicyDescription: 'Emergency cluster hold on device & proxy egress',
    basis: {
      activeEntities: 35,
      historicalComparableCampaigns: 4,
      medianTxnValue: '₹1,500',
      medianTxnsPerEntity: 8,
      projectionMethod: 'Capacity based on 35 active burner sessions'
    },
    signals: [
      { name: 'Volume Anomaly', weight: 0.25, intensity: 0.95, value: '14.2x baseline' },
      { name: 'Edge Creation', weight: 0.20, intensity: 0.92, value: '35 edges/min' },
      { name: 'Device Concentration', weight: 0.20, intensity: 0.96, value: '1 emu farm' },
      { name: 'IP/ASN Concentration', weight: 0.15, intensity: 0.90, value: 'VPN Nord (Romania)' },
      { name: 'Behavioral Similarity', weight: 0.10, intensity: 0.88, value: '98% cart match' },
      { name: 'Velocity Anomaly', weight: 0.10, intensity: 0.94, value: '8.4 txns/sec' },
    ],
    suppressorCheck: {
      isLegitimate: false,
      verdict: 'CONFIRMED ANOMALOUS SYNDICATE // PROCEED TO CONTAINMENT',
      reason: 'Low device & ASN entropy (H=0.32 vs baseline H=2.85) proves concentrated machine traffic, not a legitimate promotional crowd.',
      matchedBaseline: false,
      entropyCluster: 'H = 0.32 (High Concentration)',
      entropyBaseline: 'H = 2.85 (High Diversity)',
      historicalSpikeMatch: 'No recurring promo spike signature matched for Friday 17:00 UTC.',
    },
    graph: {
      hubs: [
        { id: 'dev-emu-99', type: 'device', label: 'Emu Farm (Nexus 998a)', hash: 'fa428...998a', sub: '1 Hardware ID' },
        { id: 'ip-vpn-ro', type: 'ip', label: 'VPN Egress (185.220.101.5)', hash: 'vpn_nord...ro', sub: 'M247 Ltd ASN' },
        { id: 'inst-axis-88', type: 'instrument', label: 'Compromised Axis Card', hash: 'axis_4524...8888', sub: 'BIN 452410' },
      ],
      nodes: Array.from({ length: 12 }, (_, i) => ({
        id: i === 6 ? 'c9f8351d-4a20-4b33-8206-8b7ac4a954f1' : `mule-${i + 1}`,
        label: i === 6 ? 'Syndicate Operative 7 (Flagged)' : `Mule Acct ${i + 1}`,
        sub: i === 6 ? 'burn_target@burner.xyz' : `user_${i + 1}@ghost.cc`,
        isFlagged: true,
        txnId: i === 6 ? 'c9f8351d-4a20-4b33-8206-8b7ac4a954f1' : null,
      })),
    },
    counterfactual: [
      {
        policy: 'ALLOW',
        name: 'Allow (No Intervention)',
        fraudLoss: '₹2,450,000',
        frictionCost: '₹0',
        netExpectedValue: '-₹2,450,000',
        isRecommended: false,
        summary: 'Full campaign executes across all 35 burner accounts without impediment.',
      },
      {
        policy: 'CHALLENGE',
        name: 'Challenge (Step-Up 2FA)',
        fraudLoss: '₹750,000',
        frictionCost: '₹45,000',
        netExpectedValue: '-₹795,000',
        isRecommended: false,
        summary: 'Forces biometric/SMS step-up; bots may attempt OTP bypass on remaining accounts.',
      },
      {
        policy: 'CONTAIN',
        name: 'Contain (Cluster Isolation)',
        fraudLoss: '₹52,000',
        frictionCost: '₹12,000',
        netExpectedValue: '-₹64,000',
        isRecommended: true,
        summary: 'Freezes proxy egress & emulated device IDs instantly. Maximum expected value preservation.',
      },
    ],
    timeline: [
      {
        time: '2m ago',
        title: 'Campaign Detected & Scored 0.94',
        detail: 'Temporal engine flagged 35 new account links created within 60s under single hardware fingerprint.',
        type: 'detection',
      },
      {
        time: '1m 30s ago',
        title: 'Legitimate Suppressor Evaluated',
        detail: 'Entropy check passed (H=0.32). Confirmed malicious botnet syndicate, false alarm ruled out.',
        type: 'suppressor',
      },
      {
        time: '45s ago',
        title: 'Exposure Range Calculated',
        detail: 'Estimated financial exposure calculated at ₹1.8M – ₹2.6M (92% confidence basis).',
        type: 'exposure',
      },
    ],
  },
  {
    id: 'camp-3b4c-8812',
    name: 'Card-Testing Micro-Probing Botnet',
    merchant: 'Croma Electronics',
    category: 'electronics',
    status: 'forming',
    score: 0.89,
    confidence: 0.91,
    detectedAt: '4m ago',
    entryPoint: 'Distributed micro-transaction probing (₹100–300) across 4 rotating stolen cards & Tor proxies',
    entityCount: 40,
    exposureLow: 1900000,
    exposureHigh: 2600000,
    exposureFormatted: '₹1.9M – ₹2.6M',
    currentObserved: '₹410,000',
    exposureConfidence: 0.88,
    recommendedPolicy: 'CHALLENGE',
    recommendedPolicyDescription: 'Mandate Step-Up 2FA & Hardware Token Verification',
    basis: {
      activeEntities: 40,
      historicalComparableCampaigns: 5,
      medianTxnValue: '₹250',
      medianTxnsPerEntity: 12,
      projectionMethod: 'Capacity based on 40 active card-testing scripts'
    },
    signals: [
      { name: 'Volume Anomaly', weight: 0.25, intensity: 0.88, value: '11.8x baseline' },
      { name: 'Edge Creation', weight: 0.20, intensity: 0.85, value: '28 edges/min' },
      { name: 'Device Concentration', weight: 0.20, intensity: 0.78, value: '5 emulators' },
      { name: 'IP/ASN Concentration', weight: 0.15, intensity: 0.92, value: 'Tor Exit Nodes' },
      { name: 'Behavioral Similarity', weight: 0.10, intensity: 0.95, value: 'Scripted micro-amounts' },
      { name: 'Velocity Anomaly', weight: 0.10, intensity: 0.82, value: '6.1 txns/sec' },
    ],
    suppressorCheck: {
      isLegitimate: false,
      verdict: 'CONFIRMED ANOMALOUS BOTNET // STEP-UP CHALLENGE RECOMMENDED',
      reason: 'Decline velocity spike (82% failure rate) across rotating BINs. Suppressor verifies distributed carding attack.',
      matchedBaseline: false,
      entropyCluster: 'H = 0.88 (High Decline Velocity)',
      entropyBaseline: 'H = 3.10 (Standard Electronics Normal)',
      historicalSpikeMatch: 'No valid promotion baseline detected.',
    },
    graph: {
      hubs: [
        { id: 'dev-emu-croma', type: 'device', label: 'Probing Farms (5 Nodes)', hash: 'emu_croma...88', sub: 'Android Emulators' },
        { id: 'ip-tor-exit', type: 'ip', label: 'Tor Exit Cluster', hash: 'tor_exit...13', sub: 'Rotating IP Pool' },
        { id: 'inst-cards-4', type: 'instrument', label: '4 Stolen BINs', hash: 'bin_testing...44', sub: 'Prepaid & Stolen' },
      ],
      nodes: Array.from({ length: 10 }, (_, i) => ({
        id: `probe-bot-${i + 1}`,
        label: `Probe Bot ${i + 1}`,
        sub: `probe_${i + 1}@cardbot.cc`,
        isFlagged: true,
        txnId: 'c9f8351d-4a20-4b33-8206-8b7ac4a954f1',
      })),
    },
    counterfactual: [
      {
        policy: 'ALLOW',
        name: 'Allow (No Intervention)',
        fraudLoss: '₹2,200,000',
        frictionCost: '₹0',
        netExpectedValue: '-₹2,200,000',
        isRecommended: false,
        summary: 'Attackers find valid live cards and escalate to high-ticket electronics purchases.',
      },
      {
        policy: 'CHALLENGE',
        name: 'Challenge (Step-Up 2FA / Hardware Token)',
        fraudLoss: '₹110,000',
        frictionCost: '₹25,000',
        netExpectedValue: '-₹135,000',
        isRecommended: true,
        summary: 'Stops automated probing scripts immediately while allowing legitimate verified shoppers.',
      },
      {
        policy: 'CONTAIN',
        name: 'Contain (Hard Block)',
        fraudLoss: '₹0',
        frictionCost: '₹280,000',
        netExpectedValue: '-₹280,000',
        isRecommended: false,
        summary: 'Hard-blocks range; causes collateral disruption for shoppers sharing gateway subnets.',
      },
    ],
    timeline: [
      {
        time: '4m ago',
        title: 'Micro-Probing Anomaly Detected (Score 0.89)',
        detail: 'Rapid sequence of ₹100–300 authorizations with 82% decline rate across 4 cards.',
        type: 'detection',
      },
      {
        time: '3m ago',
        title: 'Tor Proxy Network Correlated',
        detail: 'Graph engine connected 5 distinct emulator device IDs to common Tor egress cluster.',
        type: 'suppressor',
      },
      {
        time: '1m ago',
        title: 'Policy Recommendation Computed',
        detail: 'Step-up 2FA recommended to neutralize botnet velocity with minimal merchant disruption.',
        type: 'exposure',
      },
    ],
  },
  {
    id: 'camp-1e9d-4450',
    name: 'Coordinated Mule Velocity Anomaly',
    merchant: 'Zara Fashion',
    category: 'fashion',
    status: 'watchlist',
    score: 0.62,
    confidence: 0.74,
    detectedAt: '12m ago',
    entryPoint: 'Shared device cluster with moderate transaction velocity anomaly (3.2z) and account age clustering',
    entityCount: 16,
    exposureLow: 450000,
    exposureHigh: 780000,
    exposureFormatted: '₹450K – ₹780K',
    currentObserved: '₹185,000',
    exposureConfidence: 0.72,
    recommendedPolicy: 'MONITOR',
    recommendedPolicyDescription: 'Passive graph enrichment & velocity throttling',
    basis: {
      activeEntities: 16,
      historicalComparableCampaigns: 3,
      medianTxnValue: '₹3,500',
      medianTxnsPerEntity: 3,
      projectionMethod: 'Sub-threshold monitoring cluster'
    },
    signals: [
      { name: 'Volume Anomaly', weight: 0.25, intensity: 0.60, value: '3.2x baseline' },
      { name: 'Edge Creation', weight: 0.20, intensity: 0.64, value: '8 edges/min' },
      { name: 'Device Concentration', weight: 0.20, intensity: 0.68, value: '4 linked devices' },
      { name: 'IP/ASN Concentration', weight: 0.15, intensity: 0.55, value: 'Mixed ISPs' },
      { name: 'Behavioral Similarity', weight: 0.10, intensity: 0.62, value: 'Basket variance 0.24' },
      { name: 'Velocity Anomaly', weight: 0.10, intensity: 0.58, value: '2.1 txns/sec' },
    ],
    suppressorCheck: {
      isLegitimate: false,
      verdict: 'SUB-THRESHOLD ANOMALY // WATCHLIST ACTIVE',
      reason: 'Anomaly score (0.62) is elevated but below immediate containment trigger (0.80). Monitored under watchlist.',
      matchedBaseline: true,
      entropyCluster: 'H = 1.45 (Moderate Entropy)',
      entropyBaseline: 'H = 2.10 (Fashion Normal)',
      historicalSpikeMatch: 'Matches potential mid-tier promotional influx.',
    },
    graph: {
      hubs: [
        { id: 'dev-zara-hub', type: 'device', label: '4 Linked Handsets', hash: 'watch_dev...mod', sub: 'Mobile Cluster' },
        { id: 'ip-zara-isp', type: 'ip', label: 'Residential ISP Pool', hash: 'airtel_fiber...9', sub: 'Dynamic IPs' },
      ],
      nodes: Array.from({ length: 6 }, (_, i) => ({
        id: `watch-mule-${i + 1}`,
        label: `Watch Mule ${i + 1}`,
        sub: `wm_${i + 1}@mail.com`,
        isFlagged: false,
        txnId: 'c9f8351d-4a20-4b33-8206-8b7ac4a954f1',
      })),
    },
    counterfactual: [
      {
        policy: 'ALLOW',
        name: 'Allow & Observe',
        fraudLoss: '₹450,000',
        frictionCost: '₹0',
        netExpectedValue: '-₹450,000',
        isRecommended: true,
        summary: 'Enriches graph without adding friction to potentially genuine group shoppers.',
      },
      {
        policy: 'CHALLENGE',
        name: 'Challenge (Passive 2FA)',
        fraudLoss: '₹80,000',
        frictionCost: '₹65,000',
        netExpectedValue: '-₹145,000',
        isRecommended: false,
        summary: 'Light friction applied if single-cart volume accelerates.',
      },
      {
        policy: 'CONTAIN',
        name: 'Contain (Premature Block)',
        fraudLoss: '₹0',
        frictionCost: '₹340,000',
        netExpectedValue: '-₹340,000',
        isRecommended: false,
        summary: 'Excessive false-positive friction cost exceeds projected risk.',
      },
    ],
    timeline: [
      {
        time: '12m ago',
        title: 'Placed on Watchlist (Score 0.62)',
        detail: 'Moderate velocity anomaly detected across 4 co-located mobile devices.',
        type: 'detection',
      },
      {
        time: '8m ago',
        title: 'Passive Surveillance Active',
        detail: 'Dynamic risk threshold reduced by 15% for all subsequent transactions.',
        type: 'exposure',
      },
    ],
  },
  {
    id: 'camp-77a8-1122',
    name: 'Proxy Cluster Credential Stuffing',
    merchant: 'Uber India',
    category: 'travel',
    status: 'contained',
    score: 0.91,
    confidence: 0.95,
    detectedAt: '25m ago',
    containedAt: '23m ago',
    timeToContainment: '120s',
    exposurePrevented: '₹3.2M',
    exposureFormatted: '₹3.2M (Contained)',
    currentObserved: '₹85,000',
    entityCount: 19,
    recommendedPolicy: 'CONTAIN',
    entryPoint: 'Velocity surge (15.5z) on shared proxy cluster with coordinated bot credential stuffing',
    resolution: 'Contained automatically in 120s via emergency cluster hold policy.',
    signals: [
      { name: 'Volume Anomaly', weight: 0.25, intensity: 0.92, value: '15.5x' },
      { name: 'Edge Creation', weight: 0.20, intensity: 0.88, value: '42 edges/min' },
      { name: 'Device Concentration', weight: 0.20, intensity: 0.90, value: '2 root hashes' },
      { name: 'IP/ASN Concentration', weight: 0.15, intensity: 0.94, value: 'Proxy egress' },
      { name: 'Behavioral Similarity', weight: 0.10, intensity: 0.89, value: 'Automated replay' },
      { name: 'Velocity Anomaly', weight: 0.10, intensity: 0.91, value: '12.0 ops/s' },
    ],
    suppressorCheck: {
      isLegitimate: false,
      verdict: 'CONTAINED // MITIGATION VERIFIED',
      reason: 'Automated cluster policy contained credential stuffing attack within 120s of emergence.',
      matchedBaseline: false,
    },
    graph: {
      hubs: [
        { id: 'dev-uber-emu', type: 'device', label: 'Emu Cluster (2 Hashes)', hash: 'uber_dev...1', sub: 'Contained Device' },
        { id: 'ip-uber-proxy', type: 'ip', label: 'Proxy Gateway', hash: 'uber_ip...2', sub: 'Contained IP' },
      ],
      nodes: Array.from({ length: 6 }, (_, i) => ({
        id: `uber-mule-${i + 1}`,
        label: `Mule ${i + 1}`,
        sub: `mule_${i + 1}@uberbot.cc`,
        isFlagged: true,
        txnId: 'c9f8351d-4a20-4b33-8206-8b7ac4a954f1',
      })),
    },
    counterfactual: [
      {
        policy: 'CONTAIN',
        name: 'Contain (Executed in 120s)',
        fraudLoss: '₹85,000',
        frictionCost: '₹14,000',
        netExpectedValue: '-₹99,000',
        isRecommended: true,
        summary: 'Contained in 120 seconds. Prevented ₹3.2M in projected account takeover ride abuse.',
      },
    ],
    timeline: [
      {
        time: '25m ago',
        title: 'Surge Anomaly Detected (Score 0.91)',
        detail: '15.5z velocity spike across shared proxy cluster.',
        type: 'detection',
      },
      {
        time: '23m ago',
        title: 'Contained by Autonomous Response Engine (TTC: 120s)',
        detail: 'Emergency cluster hold applied. 19 malicious accounts isolated.',
        type: 'action',
      },
    ],
  },
  {
    id: 'camp-88b9-2233',
    name: 'Flagship Electronics Card-Testing Ring',
    merchant: 'Apple Store BKC',
    category: 'electronics',
    status: 'contained',
    score: 0.88,
    confidence: 0.93,
    detectedAt: '45m ago',
    containedAt: '42m ago',
    timeToContainment: '163s',
    exposurePrevented: '₹5.7M',
    exposureFormatted: '₹5.7M (Contained)',
    currentObserved: '₹140,000',
    entityCount: 29,
    recommendedPolicy: 'CONTAIN',
    entryPoint: 'High-velocity card testing ring on flagship electronics items',
    signals: [
      { name: 'Volume Anomaly', weight: 0.25, intensity: 0.89, value: '12.4x' },
      { name: 'Edge Creation', weight: 0.20, intensity: 0.84, value: '31 edges/min' },
      { name: 'Device Concentration', weight: 0.20, intensity: 0.86, value: '2 emulator farms' },
      { name: 'IP/ASN Concentration', weight: 0.15, intensity: 0.85, value: 'Commercial VPN' },
      { name: 'Behavioral Similarity', weight: 0.10, intensity: 0.92, value: 'Identical cart payload' },
      { name: 'Velocity Anomaly', weight: 0.10, intensity: 0.88, value: '9.2 ops/s' },
    ],
    suppressorCheck: {
      isLegitimate: false,
      verdict: 'CONTAINED // MITIGATION VERIFIED',
      reason: 'Lead analyst applied step-up verification containment in 163s.',
      matchedBaseline: false,
    },
    graph: {
      hubs: [
        { id: 'dev-apple-emu', type: 'device', label: '2 Emulator Farms', hash: 'apple_dev...1', sub: 'Isolated' },
        { id: 'ip-apple-vpn', type: 'ip', label: 'Commercial VPN', hash: 'apple_ip...2', sub: 'Isolated' },
      ],
      nodes: Array.from({ length: 6 }, (_, i) => ({
        id: `apple-mule-${i + 1}`,
        label: `Mule ${i + 1}`,
        sub: `apple_mule_${i + 1}@ghost.cc`,
        isFlagged: true,
        txnId: 'c9f8351d-4a20-4b33-8206-8b7ac4a954f1',
      })),
    },
    counterfactual: [
      {
        policy: 'CONTAIN',
        name: 'Contain (Executed in 163s)',
        fraudLoss: '₹140,000',
        frictionCost: '₹22,000',
        netExpectedValue: '-₹162,000',
        isRecommended: true,
        summary: 'Lead Analyst enforced step-up containment in 163s. Prevented ₹5.7M fraud.',
      },
    ],
    timeline: [
      {
        time: '45m ago',
        title: 'Card Testing Ring Detected (Score 0.88)',
        detail: 'High-frequency transactions against Apple Store BKC merchant portal.',
        type: 'detection',
      },
      {
        time: '42m ago',
        title: 'Containment Enforced (TTC: 163s)',
        detail: 'Step-up 2FA and card range restrictions applied.',
        type: 'action',
      },
    ],
  }
];

export const MOCK_TRANSACTION_INVESTIGATION = {
  id: 'c9f8351d-4a20-4b33-8206-8b7ac4a954f1',
  campaignId: 'camp-7f8a-9921',
  timestamp: 'Just now (18s ago)',
  amount: '₹1,25,000',
  amountPaise: 12500000,
  merchant: 'Croma Electronics',
  merchantCategory: 'electronics',
  customer: {
    name: 'Syndicate Operative 7',
    email: 'burn_target@burner.xyz',
    phone: '+919188472910',
    trustScore: 0.10,
    accountAge: '0 days (0-day burner)',
    totalPriorTxns: 0,
  },
  riskScore: 77.87,
  riskLabel: 'HOLD',
  riskConfidence: 0.94,
  instrument: {
    type: 'Card',
    name: 'Stolen Axis Bank Platinum (BIN 452410)',
    hash: 'stolen_axis_card_4524_xxxx_9999',
  },
  device: {
    type: 'Android Emulator',
    hash: 'emu_device_nexus_998a',
    firstSeen: '3 days ago',
    linkedAccountsCount: 7,
  },
  ip: {
    address: '185.220.101.5 (VPN Exit)',
    asn: 'M247 Ltd (Hosting/VPN)',
    location: 'Bucharest, Romania',
    hash: 'vpn_exit_185.220.101.5',
  },
  evidenceList: [
    {
      id: 'ev-1',
      severity: 'CRITICAL',
      toolCall: 'get_device_history(fingerprint_hash="fa428...998a")',
      finding: 'Device is an active Android emulator instance linked to 7 different newly registered accounts in 72 hours.',
      evidenceScore: '0.4369',
    },
    {
      id: 'ev-2',
      severity: 'CRITICAL',
      toolCall: 'get_transaction_history(customer_id="cust-burn-07")',
      finding: 'Transaction amount ₹1,25,000 exceeds 0-day account baseline ratio by 36.3x.',
      evidenceScore: '0.3634',
    },
    {
      id: 'ev-3',
      severity: 'HIGH',
      toolCall: 'get_ip_history(ip_hash="vpn_exit_185.220.101.5")',
      finding: 'IP is a known commercial VPN exit node (M247 Ltd ASN) with 94.2% proxy concentration.',
      evidenceScore: '0.0422',
    },
    {
      id: 'ev-4',
      severity: 'HIGH',
      toolCall: 'get_customer_history(customer_id="cust-burn-07")',
      finding: 'Account created 12 minutes prior to transaction with 0-day burner domain (@burner.xyz). Zero prior legitimate history.',
      evidenceScore: '0.0380',
    },
    {
      id: 'ev-5',
      severity: 'HIGH',
      toolCall: 'get_related_accounts(device_hash="fa428...998a")',
      finding: 'High failed authorization velocity across related cluster accounts within 30-minute window.',
      evidenceScore: '0.0304',
    },
    {
      id: 'ev-6',
      severity: 'MEDIUM',
      toolCall: 'get_instrument_history(instrument_hash="stolen_axis_card_4524_xxxx_9999")',
      finding: 'Instrument trust score evaluation confirms high-risk carding syndicate profile.',
      evidenceScore: '0.0093',
    },
  ],
  rawToolCalls: [
    {
      tool: 'get_device_history',
      params: { fingerprint_hash: 'fa428...998a', lookback_days: 7 },
      output: {
        is_emulator: true,
        emulator_type: 'Nexus 5X API 28',
        linked_customer_count: 7,
        associated_merchants: ['Croma Electronics', 'Steam Games & Vouchers'],
        risk_flags: ['ROOTED', 'HOOKING_FRAMEWORK_DETECTED', 'CANVAS_SPOOFING'],
      },
    },
    {
      tool: 'get_ip_history',
      params: { ip_hash: 'vpn_exit_185.220.101.5' },
      output: {
        is_proxy: true,
        is_vpn: true,
        is_tor: false,
        asn_organization: 'M247 Ltd',
        country: 'RO',
        threat_score: 0.94,
      },
    },
    {
      tool: 'get_related_accounts',
      params: { root_type: 'device', depth: 2 },
      output: {
        cluster_id: 'camp-7f8a-9921',
        connected_nodes: 35,
        shared_instruments: 4,
        shared_ips: 2,
        density: 0.88,
      },
    },
    {
      tool: 'get_customer_history',
      params: { customer_id: 'cust-burn-07' },
      output: {
        account_created_at: '2026-09-01T17:15:00Z',
        trust_score: 0.10,
        email_domain: 'burner.xyz',
        prior_successful_txns: 0,
      },
    },
  ],
  shapBreakdown: [
    { feature: 'device_concentration', value: 0.4369, formatted: '+0.4369', color: 'bg-orange-500' },
    { feature: 'amount_vs_avg_ratio', value: 0.3634, formatted: '+0.3634', color: 'bg-orange-500' },
    { feature: 'ip_asn_concentration', value: 0.0422, formatted: '+0.0422', color: 'bg-orange-600' },
    { feature: 'account_age_days', value: 0.0380, formatted: '+0.0380', color: 'bg-amber-500' },
    { feature: 'failed_count_30m', value: 0.0304, formatted: '+0.0304', color: 'bg-amber-600' },
    { feature: 'trust_score', value: 0.0093, formatted: '+0.0093', color: 'bg-amber-600' },
  ],
  counterfactual: [
    {
      policy: 'ALLOW',
      name: 'Allow (Approve)',
      fraudLoss: '₹97,337.50',
      frictionCost: '₹0.00',
      netExpectedValue: '-₹97,337.50',
      isRecommended: false,
      summary: '100% loss incurred upon impending chargeback; account confirmed burner.',
    },
    {
      policy: 'VERIFY',
      name: 'Verify (Step-Up 2FA)',
      fraudLoss: '₹14,600.63',
      frictionCost: '₹2,213.00',
      netExpectedValue: '-₹16,813.63',
      isRecommended: false,
      summary: 'Forces biometric/SMS 2FA; may be bypassed if bot operator has SIM intercept.',
    },
    {
      policy: 'HOLD',
      name: 'Hold (Manual Queue Review)',
      fraudLoss: '₹1,946.75',
      frictionCost: '₹5,532.50',
      netExpectedValue: '-₹7,479.25',
      isRecommended: true,
      summary: 'Freezes transaction authorization immediately for analyst review. Optimal net expected value.',
    },
    {
      policy: 'BLOCK',
      name: 'Block (Hard Decline)',
      fraudLoss: '₹0.00',
      frictionCost: '₹27,662.50',
      netExpectedValue: '-₹27,662.50',
      isRecommended: false,
      summary: 'Hard decline with permanent payment instrument blacklisting across network.',
    },
  ],
  graph: {
    hubs: [
      { id: 'dev-emu-99', type: 'device', label: 'Emu Farm (Nexus 998a)', hash: 'fa428...998a', sub: 'Linked to 7 Mules' },
      { id: 'ip-vpn-ro', type: 'ip', label: 'VPN Egress (185.220.101.5)', hash: 'vpn_nord...ro', sub: 'Romania Egress' },
      { id: 'inst-axis-88', type: 'instrument', label: 'Stolen Axis Card', hash: 'axis_4524...8888', sub: 'Flagged BIN' },
    ],
    nodes: [
      { id: 'c9f8351d-4a20-4b33-8206-8b7ac4a954f1', label: 'Syndicate Operative 7 (Subject)', sub: 'burn_target@burner.xyz', isFlagged: true },
      { id: 'mule-1', label: 'Syndicate Operative 1', sub: 'temp_user_1@mail.cc', isFlagged: true },
      { id: 'mule-2', label: 'Syndicate Operative 2', sub: 'temp_user_2@mail.cc', isFlagged: true },
      { id: 'mule-3', label: 'Syndicate Operative 3', sub: 'temp_user_3@mail.cc', isFlagged: true },
    ],
  },
};

export const MOCK_REVIEW_QUEUE = [
  {
    id: 'queue-item-1',
    kind: 'CAMPAIGN',
    targetId: 'camp-7f8a-9921',
    title: 'Voucher Abuse Syndicate',
    merchant: 'Steam Games & Vouchers',
    category: 'digital_goods',
    score: 0.94,
    scoreDisplay: '0.94',
    status: 'forming',
    recommendedPolicy: 'CONTAIN',
    exposureOrAmount: '₹1.8M – ₹2.6M',
    exposureType: 'Exposure at Risk',
    detectedAt: '2m ago',
    urgency: 'CRITICAL',
    slaRemaining: '1m 40s',
    entitiesCount: 35,
    summary: 'Coordinated emulator voucher farm probing across 35 virtual accounts with Romanian VPN egress.',
  },
  {
    id: 'queue-item-2',
    kind: 'TRANSACTION',
    targetId: 'c9f8351d-4a20-4b33-8206-8b7ac4a954f1',
    title: 'Syndicate Operative 7 (0-day burner)',
    merchant: 'Croma Electronics',
    category: 'electronics',
    score: 77.87,
    scoreDisplay: '77.87 / 100',
    status: 'flagged',
    recommendedPolicy: 'HOLD',
    exposureOrAmount: '₹1,25,000',
    exposureType: 'Transaction Amount',
    detectedAt: '18s ago',
    urgency: 'HIGH',
    slaRemaining: '42s',
    entitiesCount: 1,
    summary: 'High-value electronics authorization flagged for emulator device fingerprint and rotating BIN.',
  },
  {
    id: 'queue-item-3',
    kind: 'CAMPAIGN',
    targetId: 'camp-3b4c-8812',
    title: 'Card-Testing Micro-Probing Botnet',
    merchant: 'Croma Electronics',
    category: 'electronics',
    score: 0.89,
    scoreDisplay: '0.89',
    status: 'forming',
    recommendedPolicy: 'CHALLENGE',
    exposureOrAmount: '₹1.9M – ₹2.6M',
    exposureType: 'Exposure at Risk',
    detectedAt: '4m ago',
    urgency: 'CRITICAL',
    slaRemaining: '3m 15s',
    entitiesCount: 40,
    summary: 'Micro-transaction probing across 4 rotating stolen cards & Tor proxy pool with 82% failure rate.',
  },
  {
    id: 'queue-item-4',
    kind: 'CAMPAIGN',
    targetId: 'camp-1e9d-4450',
    title: 'Coordinated Mule Velocity Anomaly',
    merchant: 'Zara Fashion',
    category: 'fashion',
    score: 0.62,
    scoreDisplay: '0.62',
    status: 'watchlist',
    recommendedPolicy: 'MONITOR',
    exposureOrAmount: '₹450K – ₹780K',
    exposureType: 'Surveillance Exposure',
    detectedAt: '12m ago',
    urgency: 'MEDIUM',
    slaRemaining: '18m 00s',
    entitiesCount: 16,
    summary: 'Sub-threshold velocity anomaly across 4 co-located handsets under passive monitoring.',
  },
];

export const MOCK_NORMAL_FLOW = {
  cleanTxnRate: '99.42%',
  avgScoringLatency: '11.8ms',
  activeMerchantsCount: 8,
  recentCleanVolume: '₹24.8M / hr',
  suppressionEvent: {
    merchant: 'Flipkart Supermart',
    event: 'Flash Sale Promo Surge (50 txns / 250s)',
    entropyH: '3.84 (High Diversity)',
    suppressorVerdict: 'PROVEN LEGITIMATE CROWD // SUPPRESSED FALSE ALARM',
  }
};

export const MOCK_NORMAL_TRANSACTIONS = [
  {
    id: 'txn-9921-a4f',
    timestamp: '4s ago',
    merchant: 'Swiggy Gourmet',
    customer: 'Priya N. (Trust: 0.96)',
    amount: '₹1,420',
    instrument: 'UPI / HDFC Bank',
    latency: '9.2ms',
    riskScore: 0.04,
    status: 'ALLOWED',
  },
  {
    id: 'txn-9920-b8c',
    timestamp: '12s ago',
    merchant: 'Uber India',
    customer: 'Rohan M. (Trust: 0.91)',
    amount: '₹680',
    instrument: 'Credit Card / ICICI',
    latency: '11.4ms',
    riskScore: 0.06,
    status: 'ALLOWED',
  },
  {
    id: 'txn-9919-d1e',
    timestamp: '18s ago',
    merchant: 'Amazon India',
    customer: 'Ananya S. (Trust: 0.98)',
    amount: '₹4,899',
    instrument: 'UPI / Axis Bank',
    latency: '8.7ms',
    riskScore: 0.03,
    status: 'ALLOWED',
  },
  {
    id: 'txn-9918-f7b',
    timestamp: '25s ago',
    merchant: 'Zara Fashion',
    customer: 'Vikram K. (Trust: 0.89)',
    amount: '₹8,450',
    instrument: 'Credit Card / SBI',
    latency: '12.1ms',
    riskScore: 0.08,
    status: 'ALLOWED',
  },
  {
    id: 'txn-9917-c3a',
    timestamp: '34s ago',
    merchant: 'Croma Electronics',
    customer: 'Neha G. (Trust: 0.94)',
    amount: '₹18,990',
    instrument: 'EMI Card / HDFC',
    latency: '10.5ms',
    riskScore: 0.05,
    status: 'ALLOWED',
  },
  {
    id: 'txn-9916-e5d',
    timestamp: '42s ago',
    merchant: 'Flipkart Supermart',
    customer: 'Devendra R. (Trust: 0.92)',
    amount: '₹2,340',
    instrument: 'UPI / GPay',
    latency: '9.8ms',
    riskScore: 0.04,
    status: 'ALLOWED',
  },
];
